In [38]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [39]:
df = pd.read_csv("student_pass_dataset.csv")

In [40]:
df.shape

(300, 4)

In [41]:
df.head()

   hours_studied  attendance_pct  previous_score  passed
0            3.7              43              41       0
1            9.5              72              48       1
2            7.3              72              42       1
3            6.0              78              36       1
4            1.6              84              38       0

In [42]:
x = df.drop(["passed"],axis=1)

In [43]:
x.head()

   hours_studied  attendance_pct  previous_score
0            3.7              43              41
1            9.5              72              48
2            7.3              72              42
3            6.0              78              36
4            1.6              84              38

In [44]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [11]:
x_scaled

array([[-0.42707672, -1.52500797, -1.06771426],
       [ 1.54718867,  0.07542259, -0.68703515],
       [ 0.79832938,  0.07542259, -1.01333153],
       [ 0.35582162,  0.40654615, -1.33962791],
       [-1.14189694,  0.73766972, -1.23086245],
       [-1.14189694,  1.56547863, -0.0344424 ],
       [-1.48228753,  0.02023533, -0.9589488 ],
       [ 1.2748762 , -0.6420118 , -0.36073877],
       [ 0.35582162,  0.95841876,  0.12870579],
       [ 0.73025127, -0.80757358,  0.78129855],
       [-1.61844376, -0.25570097, -1.50277609],
       [ 1.61526678, -1.41463345,  1.16197766],
       [ 1.13871997, -1.58019523,  0.56376763],
       [-0.97170165,  1.51029137, -1.39401064],
       [-1.07381883,  1.06879328,  1.4338913 ],
       [-1.07381883,  0.6272952 ,  1.59703949],
       [-0.66535013, -0.31088824, -1.44839336],
       [ 0.08350916, -1.13869715, -0.68703515],
       [-0.22284237, -1.19388441,  1.16197766],
       [-0.69938919, -0.86276084,  0.99882947],
       [ 0.38986068,  0.13060985, -1.01333153],
       [-1.20997506,  0.68248246, -0.90456607],
       [-0.69938919,  0.51692068, -0.36073877],
       [-0.42707672, -0.75238632,  0.01994033],
       [-0.12072519,  1.45510411,  0.5093849 ],
       [ 1.00256373,  0.73766972, -0.36073877],
       [-1.00574071,  0.13060985, -0.0344424 ],
       [ 0.0494701 ,  0.35135889,  0.99882947],
       [ 0.32178257, -0.31088824, -1.55715882],
       [-1.51632659, -0.86276084, -0.79580061],
       [ 0.38986068, -0.53163728,  0.83568128],
       [-1.10785789,  0.79285698,  1.48827403],
       [-1.44824847, -1.63538249,  0.12870579],
       [ 1.54718867, -1.30425893,  0.23747125],
       [ 1.61526678, -1.52500797, -1.28524518],
       [ 1.07064185, -1.58019523, -0.08882512],
       [-0.66535013,  1.12398054,  0.23747125],
       [-1.34613129,  0.6272952 , -0.79580061],
       [ 0.62813409, -0.14532645, -0.68703515],
       [-0.18880331, -1.35944619, -0.30635604],
       [-1.27805318, -0.09013919, -1.61154155],
       [ 0.01543104, -0.14532645, -0.52388696],
       [-1.5844047 , -1.13869715, -0.90456607],
       [ 1.41103243, -0.25570097, -0.52388696],
       [-0.80150636, -0.3660755 , -1.23086245],
       [ 0.56005597,  0.35135889,  1.48827403],
       [-0.63131107,  0.40654615,  0.45500217],
       [ 0.08350916, -1.52500797,  0.72691582],
       [ 0.18562633, -0.47645002,  1.10759493],
       [-1.07381883,  0.40654615,  0.07432306],
       [ 1.61526678, -0.03495193, -1.33962791],
       [ 0.96852467,  1.12398054,  0.23747125],
       [ 1.51314961,  0.51692068,  0.40061944],
       [ 1.34295432, -1.13869715,  0.94444674],
       [ 0.35582162, -1.46982071, -0.14320785],
       [ 1.44507149,  0.46173341, -1.23086245],
       [-1.38017035, -1.58019523, -0.68703515],
       [-1.00574071,  0.24098437, -0.36073877],
       [-1.51632659,  1.39991685,  0.61815036],
       [-0.56323295,  0.24098437,  0.34623671],
       [-0.3589986 , -0.42126276, -0.4151215 ],
       [-0.7674673 ,  0.46173341,  1.81457041],
       [ 1.13871997, -0.20051371,  0.45500217],
       [-0.46111578,  0.13060985, -0.85018334],
       [-0.73342824,  1.39991685, -1.28524518],
       [ 0.15158727, -0.42126276, -1.12209699],
       [-1.20997506,  1.51029137, -0.79580061],
       [ 1.03660279,  1.28954233, -1.12209699],
       [-1.44824847, -1.02832262, -1.01333153],
       [ 1.6833449 , -1.46982071, -0.63265242],
       [ 0.93448562, -1.35944619, -1.06771426],
       [-1.00574071, -1.63538249,  1.48827403],
       [-1.65248282, -1.35944619, -1.39401064],
       [ 1.10468091,  0.57210794,  0.18308852],
       [ 0.73025127, -1.46982071, -0.19759058],
       [ 0.79832938, -0.6420118 ,  1.81457041],
       [ 0.93448562,  1.12398054, -1.28524518],
       [-1.44824847, -1.63538249, -0.25197331],
       [-0.46111578,  1.01360602,  1.76018768],
       [-1.27805318, -0.75238632,  1.37950857],
       [ 1.24083714, -1.30425893,  1.21636039],
       [ 0.42389974,  0.6272952 , -0.74141788],
       [-0.56323295,  0.40654615, -1.06771426],
       [-1.48228753,  1.23435506,  0.67253309],
       [-0.63131107,  0.73766972,  1.59703949],
       [-0.56323295,  0.95841876,  0.29185398],
       [ 0.79832938, -0.75238632,  0.34623671],
       [ 0.49197786, -1.08350989, -0.68703515],
       [ 1.34295432,  0.79285698,  1.0532122 ],
       [-0.08668614,  0.95841876, -1.01333153],
       [-1.27805318,  1.56547863, -0.52388696],
       [ 0.73025127, -0.31088824, -0.14320785],
       [ 0.90044656, -0.47645002,  0.12870579],
       [ 0.21966539,  0.9032315 , -0.79580061],
       [ 0.93448562, -0.58682454, -1.28524518],
       [-0.01860802,  1.39991685,  0.5093849 ],
       [ 0.08350916,  1.1791678 , -0.63265242],
       [-0.22284237, -0.25570097,  0.40061944],
       [-1.5844047 ,  0.79285698, -1.12209699],
       [-1.31209224,  0.79285698,  0.01994033],
       [-1.5844047 , -1.35944619,  0.23747125],
       [ 0.49197786,  1.28954233, -1.50277609],
       [-0.63131107, -0.03495193, -0.46950423],
       [ 0.0494701 ,  1.06879328, -1.17647972],
       [ 1.41103243, -0.6420118 , -1.44839336],
       [-0.83554542,  1.28954233,  1.81457041],
       [-0.29092049, -0.42126276, -0.52388696],
       [ 0.90044656, -1.63538249,  1.21636039],
       [-0.90362354,  1.28954233, -0.74141788],
       [-1.41420941, -1.41463345,  0.72691582],
       [-0.69938919, -0.6420118 ,  0.99882947],
       [-1.14189694,  1.45510411,  0.45500217],
       [ 1.47911055,  1.45510411,  0.01994033],
       [ 1.07064185,  0.18579711, -0.19759058],
       [ 0.4579388 ,  0.40654615, -0.4151215 ],
       [ 1.2748762 , -0.20051371,  1.59703949],
       [ 1.03660279, -0.69719906,  1.27074311],
       [-1.03977977, -0.58682454,  1.76018768],
       [ 1.34295432,  0.51692068, -1.23086245],
       [ 0.15158727,  0.79285698,  0.94444674],
       [ 1.07064185,  0.9032315 ,  1.65142222],
       [ 1.37699337,  0.9032315 , -1.01333153],
       [-0.59727201, -1.41463345, -1.44839336],
       [-1.31209224, -0.03495193,  0.94444674],
       [-0.90362354, -1.52500797,  0.34623671],
       [-0.22284237,  0.13060985,  1.32512584],
       [ 1.10468091, -0.25570097, -1.17647972],
       [ 1.24083714,  1.23435506,  1.16197766],
       [-1.65248282, -0.53163728, -0.9589488 ],
       [ 0.0494701 , -1.30425893, -1.06771426],
       [-0.25688143, -1.19388441, -1.06771426],
       [-0.93766259,  0.84804424,  1.21636039],
       [-1.27805318,  0.35135889,  0.67253309],
       [-0.52919389, -1.35944619,  0.18308852],
       [ 1.51314961, -1.41463345, -0.4151215 ],
       [-0.59727201,  0.6272952 ,  1.4338913 ],
       [ 0.08350916, -1.46982071, -0.25197331],
       [ 0.69621221,  1.01360602,  1.21636039],
       [-0.46111578,  0.6272952 , -0.08882512],
       [ 1.61526678, -1.41463345, -0.30635604],
       [ 1.58122772, -1.41463345, -0.0344424 ],
       [-0.83554542,  1.56547863, -0.57826969],
       [ 0.01543104, -0.47645002,  0.99882947],
       [-0.66535013, -0.47645002,  0.12870579],
       [-0.73342824,  1.01360602, -0.85018334],
       [-1.55036564,  1.45510411,  1.48827403],
       [ 0.38986068,  1.56547863, -0.30635604],
       [ 0.01543104,  0.79285698,  0.23747125],
       [-1.51632659, -0.42126276,  1.54265676],
       [-0.73342824, -1.41463345,  0.56376763],
       [ 1.41103243,  0.9032315 , -1.23086245],
       [-0.86958448,  0.18579711,  1.65142222],
       [-1.20997506, -0.31088824,  0.56376763],
       [-0.01860802,  1.28954233, -0.46950423],
       [ 1.6833449 , -1.30425893, -1.17647972],
       [-0.86958448, -0.03495193,  1.16197766],
       [ 0.59409503, -1.63538249,  0.5093849 ],
       [ 0.90044656, -0.14532645,  0.23747125],
       [-0.86958448, -1.52500797,  1.48827403],
       [ 0.79832938, -1.30425893,  1.10759493],
       [-0.42707672, -1.30425893, -1.12209699],
       [ 0.4579388 ,  0.46173341, -0.57826969],
       [ 0.4579388 ,  0.79285698, -0.79580061],
       [ 0.15158727,  0.24098437,  0.94444674],
       [-1.38017035,  1.51029137, -1.55715882],
       [ 1.17275902, -0.47645002,  0.34623671],
       [-0.59727201, -0.75238632,  1.0532122 ],
       [-1.03977977,  1.1791678 ,  1.4338913 ],
       [-1.55036564, -0.97313536, -0.46950423],
       [ 0.32178257,  1.51029137,  1.21636039],
       [ 0.62813409, -1.63538249, -1.28524518],
       [-1.61844376,  1.51029137,  1.32512584],
       [ 0.0494701 , -1.52500797, -1.23086245],
       [-0.90362354,  1.23435506, -0.25197331],
       [ 0.52601692,  0.07542259,  1.16197766],
       [-1.10785789,  1.62066589, -1.12209699],
       [ 0.66217315, -1.46982071, -0.85018334],
       [-0.3589986 ,  0.13060985,  0.89006401],
       [ 1.51314961,  1.51029137,  0.89006401],
       [-1.20997506,  0.02023533,  0.61815036],
       [-0.52919389,  0.40654615,  0.78129855],
       [-1.31209224,  0.6272952 ,  0.23747125],
       [ 1.44507149, -0.20051371, -0.79580061],
       [ 1.30891526,  0.40654615, -0.46950423],
       [-0.80150636,  0.24098437, -1.01333153],
       [ 0.56005597,  1.28954233,  1.54265676],
       [ 1.10468091, -1.52500797,  0.40061944],
       [ 0.21966539, -0.75238632, -0.25197331],
       [ 0.11754821,  1.45510411, -0.0344424 ],
       [-0.86958448,  1.23435506,  1.70580495],
       [-1.38017035, -0.20051371, -1.12209699],
       [ 1.37699337,  0.35135889,  0.40061944],
       [ 1.37699337, -0.75238632,  0.12870579],
       [ 0.4579388 , -1.08350989,  0.5093849 ],
       [-0.52919389, -0.14532645, -1.61154155],
       [-0.49515484, -0.53163728,  1.4338913 ],
       [ 0.79832938,  0.24098437,  1.65142222],
       [ 1.37699337, -1.41463345,  0.34623671],
       [ 1.34295432,  1.51029137,  0.78129855],
       [ 0.96852467,  1.56547863,  1.59703949],
       [ 0.49197786,  0.6272952 ,  0.83568128],
       [-1.41420941,  0.07542259, -1.12209699],
       [-1.14189694, -0.6420118 ,  0.34623671],
       [ 1.37699337,  1.01360602,  0.45500217],
       [ 0.38986068,  0.57210794, -0.14320785],
       [-1.65248282, -1.13869715,  0.94444674],
       [-1.34613129,  1.34472959,  1.65142222],
       [ 0.56005597,  1.01360602,  1.59703949],
       [-1.65248282,  1.45510411, -0.08882512],
       [-1.14189694,  0.73766972, -1.28524518],
       [ 0.18562633,  0.35135889,  1.81457041],
       [ 0.66217315, -0.31088824,  1.32512584],
       [ 0.52601692,  1.39991685, -1.23086245],
       [-0.93766259,  1.1791678 ,  1.59703949],
       [ 0.73025127, -1.52500797,  1.4338913 ],
       [-0.86958448, -1.58019523,  0.18308852],
       [-0.56323295, -0.42126276,  0.40061944],
       [ 0.8664075 ,  1.01360602, -0.25197331],
       [ 0.52601692,  1.56547863, -1.44839336],
       [ 1.20679808, -1.19388441, -0.46950423],
       [ 0.56005597,  0.29617163,  1.16197766],
       [ 0.25370445, -0.42126276, -1.66592428],
       [-1.38017035,  1.51029137, -0.46950423],
       [-0.42707672,  1.12398054, -0.25197331],
       [-0.7674673 ,  1.06879328,  0.23747125],
       [-0.86958448, -0.14532645,  1.59703949],
       [ 1.61526678, -0.31088824, -0.4151215 ],
       [-0.3589986 , -0.80757358, -0.4151215 ],
       [ 1.34295432, -1.52500797,  0.94444674],
       [ 0.4579388 ,  1.1791678 , -0.08882512],
       [ 1.00256373,  1.01360602, -0.85018334],
       [ 0.01543104,  1.62066589, -0.08882512],
       [ 0.28774351,  1.62066589, -1.17647972],
       [-0.01860802,  0.13060985, -1.06771426],
       [-1.00574071,  0.84804424,  0.07432306],
       [ 0.76429032,  1.45510411, -0.19759058],
       [-0.73342824,  1.12398054,  1.54265676],
       [-1.61844376, -0.86276084, -0.36073877],
       [ 0.52601692, -0.20051371,  0.40061944],
       [-1.07381883, -1.24907167,  0.56376763],
       [ 1.51314961,  1.45510411, -1.61154155],
       [ 1.54718867,  0.29617163,  0.67253309],
       [ 1.41103243, -0.9179481 , -1.01333153],
       [-0.42707672,  0.51692068,  1.70580495],
       [-1.61844376,  0.35135889, -1.12209699],
       [ 1.47911055, -0.53163728, -0.19759058],
       [-0.22284237, -1.30425893, -1.33962791],
       [ 1.61526678,  0.51692068,  1.86895314],
       [ 1.58122772,  0.02023533,  0.12870579],
       [ 1.20679808,  0.84804424,  0.45500217],
       [-0.69938919,  0.02023533, -1.44839336],
       [-0.3589986 ,  1.12398054,  0.99882947],
       [ 1.20679808,  0.13060985, -0.90456607],
       [-0.59727201,  0.18579711,  1.48827403],
       [-1.10785789,  1.23435506, -0.9589488 ],
       [ 0.21966539, -0.3660755 , -1.01333153],
       [ 1.51314961, -1.24907167, -1.55715882],
       [ 0.69621221, -1.58019523,  0.01994033],
       [ 0.25370445,  0.79285698,  0.34623671],
       [-1.34613129,  0.35135889, -1.44839336],
       [ 0.42389974,  0.6272952 ,  1.0532122 ],
       [ 1.6833449 , -0.97313536, -0.08882512],
       [-1.20997506, -1.24907167,  0.18308852],
       [ 0.08350916, -1.63538249, -0.08882512],
       [ 1.30891526, -0.53163728, -0.25197331],
       [ 0.83236844,  0.24098437,  0.29185398],
       [ 0.69621221, -0.3660755 , -1.12209699],
       [ 0.69621221, -0.25570097, -1.01333153],
       [-0.46111578,  1.28954233,  1.37950857],
       [-0.69938919, -0.53163728,  1.65142222],
       [ 1.07064185,  0.02023533, -0.36073877],
       [ 1.07064185,  0.9032315 , -0.68703515],
       [ 1.2748762 , -0.3660755 ,  0.61815036],
       [ 1.41103243,  0.35135889, -0.19759058],
       [ 0.0494701 ,  1.1791678 , -1.55715882],
       [ 0.01543104,  1.45510411, -1.12209699],
       [ 1.03660279, -1.19388441,  0.89006401],
       [ 0.52601692,  1.39991685,  0.67253309],
       [ 0.69621221, -0.03495193, -1.55715882],
       [ 1.03660279, -0.86276084, -0.90456607],
       [ 1.34295432, -0.14532645, -0.85018334],
       [-0.52919389,  1.56547863,  0.72691582],
       [-0.39303766, -0.03495193, -1.61154155],
       [-1.38017035, -0.58682454, -1.28524518],
       [ 0.28774351,  0.40654615,  1.16197766],
       [-1.55036564, -0.9179481 , -1.01333153],
       [-0.08668614, -1.41463345,  0.61815036],
       [ 0.15158727, -1.24907167, -0.85018334],
       [-0.69938919, -1.24907167, -1.33962791],
       [ 0.32178257, -1.19388441, -0.79580061],
       [-1.5844047 , -1.24907167,  0.89006401],
       [-1.55036564,  0.40654615,  1.37950857],
       [ 1.10468091, -1.08350989,  1.27074311],
       [-0.46111578, -0.53163728, -0.25197331],
       [-1.24401412,  1.28954233,  0.67253309],
       [ 0.08350916, -0.14532645, -0.9589488 ],
       [ 0.93448562,  0.51692068, -0.63265242],
       [-0.93766259, -1.13869715,  1.48827403],
       [ 0.42389974, -1.02832262, -1.61154155],
       [-1.38017035, -1.58019523, -1.33962791]])

In [45]:
y = df["passed"]
y.head()

0    0
1    1
2    1
3    1
4    0
Name: passed, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split 
x_train , x_test , y_train , y_test = train_test_split(x_scaled,y,test_size=0.25,random_state=42,stratify=y)

x_train_scaled = scaler.fit_transform(x_train)   # learn + apply on train
x_test_scaled = scaler.transform(x_test)

In [48]:
from sklearn.linear_model import LogisticRegression 
lg = LogisticRegression(max_iter=1000) 

lg.fit(x_train_scaled,y_train)

LogisticRegression(max_iter=1000)

In [49]:
y_pred = lg.predict(x_test_scaled)

In [50]:
y_pred

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1])

In [51]:
y_test

289    0
173    0
266    0
177    0
99     0
      ..
140    1
235    1
174    0
36     0
200    1
Name: passed, Length: 75, dtype: int64

In [52]:
from sklearn.metrics import accuracy_score , roc_auc_score , confusion_matrix , classification_report 
print("Accuracy : ",accuracy_score(y_test,y_pred))
print("ROC Accuracy : ",roc_auc_score(y_test,y_pred))
print("Confusion Matrix :\n",confusion_matrix(y_test,y_pred))
print("Classification Report : ",classification_report(y_test,y_pred))

Accuracy :  0.7333333333333333
ROC Accuracy :  0.7297008547008547
Confusion Matrix :
 [[23 13]
 [ 7 32]]
Classification Report :                precision    recall  f1-score   support

           0       0.77      0.64      0.70        36
           1       0.71      0.82      0.76        39

    accuracy                           0.73        75
   macro avg       0.74      0.73      0.73        75
weighted avg       0.74      0.73      0.73        75